services:
  backend:
    build:
      context: ./backend # Caminho para o backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/core_notes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend # Caminho para o frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: core_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
